version: "3"
services:
  nginx:
    container_name: nginx-container
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - jenkins
    networks:
      - docker-subnet
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-container
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
      # - JENKINS_LOG=/var/jenkins_home/logs/jenkins.log
      #Nginxで設定するためにprefixを指定する
      - "JENKINS_OPTS= \
        --accessLoggerClassName=winstone.accesslog.SimpleAccessLogger \
        --prefix=/jenkins \
        --sessionTimeout=1440 \
        --simpleAccessLogger.format=combined \
        --simpleAccessLogger.file=/var/jenkins_home/logs/jenkins.log"
    volumes:
      - ./jenkins/home:/var/jenkins_home
    restart: always
    networks:
      - docker-subnet
networks:
  docker-subnet:
